### ISSUE TITLE
T430 Bios 2.81

### ISSUE THREAD

**Issue by ethanh92** [hamishcoleman/thinkpad-ec#129]
Hello, is there a way to build the patched image with BIOS 2.81 for a T430 by editing some files? Currently the patcher will only build it with BIOS 2.79. Additionally, I already have a copy g1uj48us.iso locally. Is it possible to get the patcher to use that instead of downloading g1uj46us.iso? Thanks!

**Comment by hamishcoleman** [comment]
I have updated the t430 build to be based from BIOS 2.81 (see 4b072b6444211d785008410b521a95222ff448da)

However, the EC firmware versions have not changed since BIOS 2.70, so you are completely safe to use a patched image based on an earlier version.

If you rename your g1uj48us.iso to be "g1uj48us.iso.orig" in the repository directory, then it will pick it up and use it (after checking the SHA1 checksum)
