### ISSUE TITLE
W530 modification not working

### ISSUE THREAD

**Issue by c0pter** [hamishcoleman/thinkpad-ec#13]
Yesterday I found this wonderful project. I applied W530 EC update, which I built by marking 001-005 to .OFF and enabled 006 by removing .OFF. I build the image and followed the output and 006 patch was applied properly.

After this I rebooted from the USB and EC update was programmed and after reboot laptop programmed EC firmware with high fan speed as normally.

My 9 cell battery works normally (which was working before), but third party 6-cell battery which was the reason why I made the modification, is still not working. I'm not getting any warnings / messages about non-Lenovo battery, but battery is not charging. 

If I power off the laptop, put 6-cell battery in and then insert power supply, green led is blinking couple times, then orange led starts blinking "slow" and after couple blinks it starts to blink faster. After blinking for a while it blinks once in green again and then all led activity stops.

In Windows battery state is 0% and after inserting the battery it shows for maybe 2 seconds that it's charging, but then stops and just shows that battery with 0% is inserted but it's not charging.

Any ideas? Could this be a faulty battery or could it be that I need to adjust acpi battery limits to get the battery charging (if it's on too low voltage)?

Sorry about the long report and thanks from this great project!

**Comment by hamishcoleman** [comment]
Unfortunately, I dont know that much about the battery patch - I went through all my spare batteries and it turned out that they were all genuine!

My usual suggestion would be that there was something that had caused the EC not to flash - but you have already covered that off.

I would go and look at the Lenovo LED documentation - it might be that that battery is signalling that it has no capacity (extended storage with no charge can make the battery management controller unhappy - or sometimes make the batteries unhappy) - but I'm sorry to say that it is all just a conjecture on my part.  Without hardware modifications, it will probably be hard to debug.  (If you want to investigate that avenue, I suggest you have a look at the things zmatt needed to do to make these patches: http://zmatt.net/unlocking-my-lenovo-laptop-part-1/)
